[project]
name = "defi-sentinel-contracts"
description = ""
authors = []
telemetry = true
cache_dir = "./.cache"

[contracts.stacks-passport]
path = "contracts/stacks-passport.clar"
epoch = "3.1"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
